version: "3.8"
volumes:
  docker_ingestion-volume-dags:
    external: true
  docker_ingestion-volume-dag-airflow:
    external: true
  docker_ingestion-volume-tmp:
    external: true
  es-data:

services:
  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow-webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@postgresql:5432/airflow_db
      #AIRFLOW__WEBSERVER__PORT: 8081
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    ports:
      #- "8081:8081"
      - "8081:8080"
    volumes:
      - docker_ingestion-volume-dags:/opt/airflow/dags
      - docker_ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs
      - docker_ingestion-volume-tmp:/tmp
    command: webserver
    networks:
      - openmetadata-docker_app_net

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow-scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@postgresql:5432/airflow_db
    volumes:
      - docker_ingestion-volume-dags:/opt/airflow/dags
      - docker_ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs
      - docker_ingestion-volume-tmp:/tmp
    command: scheduler
    networks:
      - openmetadata-docker_app_net

networks:
  openmetadata-docker_app_net:
    external: true

